from __future__ import annotations

import glob
import os
import logging
import json

from abc import ABC, abstractmethod
from typing import Dict, List

import networkx as nx
import numpy as np
import pandas as pd

from fuzzydata.core.artifact import Artifact
from fuzzydata.core.generator import generate_schema
from fuzzydata.core.operation import Operation


logger = logging.getLogger(__name__)


class Workflow(ABC):
    """
    Class to represent a workflow in fuzzydata, Extends DiGraph from networkx with additional metadata about
    the workflow as required.
    """
    def __init__(self, name='wf', out_directory='/tmp/fuzzydata/wf/'):
        """
        Create a new workflow with a specified name
        :param name: Name of the workflow
        :param out_directory: Output Directory for this workflow
        """

        self.name = name
        self.graph = nx.DiGraph()
        self.out_dir = out_directory
        self.artifact_dir = f"{self.out_dir}/artifacts/"
        os.makedirs(self.artifact_dir, exist_ok=True)
        self.artifact_list = []
        self.artifact_dict = {}

        self.artifact_class = None
        self.operator_class = None

        self.operation_list = []

        self.perf_df = pd.DataFrame()

        logger.info(f'Creating new Workflow {self.name}')

    def generate_next_label(self):
        return f"artifact_{len(self)}"

    @abstractmethod
    def initialize_new_artifact(self, label=None, filename=None) -> Artifact:
        pass

    def add_artifact(self, artifact: Artifact,
                     from_artifacts: List[Artifact] = None, operation: Operation = None) -> None:
        """
        Add a new artifact to the workflow with label and dataframe.
        Optionally add source label and edge information
        :param artifact: The artifact to be added
        :param from_artifacts: (optional) Source artifacts from which this new artifact was derived
        :param operation: Operation used to derive this new artifact
        """
        self.graph.add_node(artifact.label,
                            **{
                                'schema_map': artifact.schema_map,
                                'file_format': artifact.file_format,
                                'filename': artifact.filename
                            })
        v = artifact.label

        self.artifact_list.append(artifact.label)
        self.artifact_dict[artifact.label] = artifact

        if from_artifacts:
            for u in from_artifacts:
                self.graph.add_edge(u.label, v, **{
                    'operation': operation.op.__name__,
                    'args': operation.args
                })

    def generate_base_artifact(self, num_rows=100, num_cols=10, column_maps=None, label: str = None) -> None:
        """
        Create a base artifact of with given rows and columns
        :param num_rows: number of rows to be generated
        :param num_cols: number of columns to be generated
        :param column_maps: (optional) schema map for the table to be generated
        :param label: (optional) custom label for the artifact to be generated
        :return:
        """
        if not column_maps:
            column_maps = generate_schema(num_cols)
        if not label:
            label = self.generate_next_label()
        new_artifact = self.initialize_new_artifact(label=label, filename=f"{self.artifact_dir}/{label}.csv")
        new_artifact.generate(num_rows, column_maps)
        self.add_artifact(new_artifact)

    def generate_artifact_from_operation(self, artifacts: List[Artifact], op: str,
                                         args: Dict, new_label: str = None) -> None:
        """
        Generate a new artifact with source artifacts apply operation op with args parameters.
        :param new_label: Optional label annotation for the artifact to be generated. Autogenerated if not specified.
        :param artifacts: list of source artifacts for the operation to be applied.
        :param op: string label of the operation to be applied.
        :param args: dict containing all the parameters to be passed to the operation function.
        :return:
        """
        if not new_label:
            new_label = self.generate_next_label()

        operation = self.operator_class(sources=artifacts, new_label=new_label, op=op, args=args)
        new_artifact = operation.execute()
        self.add_artifact(new_artifact, from_artifacts=artifacts, operation=operation)

        # TODO: Exception Handling and return value on op failure / empty df

        # Add operation to op list
        self.operation_list.append(operation.to_dict())

        # Add performance information
        self.perf_df = self.perf_df.append({
            'src': [x.label for x in artifacts],
            'dst': [new_label],
            'op': op,
            'args': args,
            'start_time': operation.start_time,
            'end_time': operation.end_time,
            'elapsed_time': operation.get_execution_time()
        }, ignore_index=True).reset_index(drop=True)

    def serialize_workflow(self, output_dir: str = None) -> None:
        if not output_dir:
            output_dir = self.out_dir

        # Create Output Directories
        artifact_dir = f"{output_dir}/artifacts/"
        os.makedirs(artifact_dir, exist_ok=True)

        # Write out all artifacts
        for label, artifact in self.artifact_dict.items():
            logger.debug(f"Serialization {label}, {artifact.label}")
            artifact.serialize(filename=f"{artifact_dir}/{label}.{artifact.file_format}")

        # Write out Operation List JSON
        with open(f"{output_dir}/{self.name}_operations.json", 'w') as outfile:
            outfile.write(json.dumps({'name': self.name,
                                      'operation_list': [op for op in self.operation_list]
                                      }, indent=2))

        # Write out Lineage Graph
        nx.write_edgelist(self.graph, f"{output_dir}/{self.name}_gt_graph.csv")

    @classmethod
    def load_workflow(cls, input_dir: str, out_directory: str, replay=False) -> Workflow:
        try:
            artifact_dir = f"{input_dir}/artifacts/"
            operations_file = glob.glob(f"{input_dir}/*_operations.json")[0]

            with open(operations_file, 'r') as infile:
                ops = json.load(infile)

            workflow = cls(name=ops['name'], out_directory=out_directory)

            if replay:
                workflow.replay_op_list(artifact_dir, op_list=ops['operation_list'])
                workflow.write_perf()

            workflow.graph = nx.read_edgelist(f"{input_dir}/{workflow.name}_gt_graph.csv")

            return workflow

        except FileNotFoundError as e:
            logger.error(f"Error Loading Workflow from {input_dir}: {e}")

    def replay_op_list(self, artifact_dir: str, op_list=None) -> None:
        for op in op_list:
            for source in op['sources']:
                if source not in self.artifact_dir:
                    source_artifact = self.initialize_new_artifact(label=source)
                    source_artifact.deserialize(filename=f"{artifact_dir}/{source}.{source_artifact.file_format}")
                    self.add_artifact(source_artifact)

            self.generate_artifact_from_operation([self.artifact_dict[x] for x in op['sources']],
                                                  op['op'], op['args'], new_label=op['new_label'])

    def write_perf(self, filename=None):
        if not filename:
            filename = f"{self.out_dir}/{self.name}_perf.csv"

        self.perf_df.to_csv(filename)

    def select_random_artifact(self, bfactor=1.0, exclude: List[str] = None) -> Artifact:
        viable_artifacts = dict(filter(lambda x: x[0] not in exclude, self.artifact_dict.items()))
        size = len(viable_artifacts)
        i = np.arange(size)  # an array of the index value for weighting
        prob = np.exp(i/bfactor)  # higher weights for larger index values
        prob /= prob.sum()
        return self.artifact_dict[np.random.choice(list(viable_artifacts.keys()), 1)[0]]

    def __len__(self):
        return len(self.artifact_list)

    def __getitem__(self, item):
        return self.artifact_dict[item]
