import modin

from fuzzydata.clients.pandas import DataFrameArtifact, DataFrameOperation
from fuzzydata.core.workflow import Workflow


class ModinArtifact(DataFrameArtifact):

    def __init__(self, *args, **kwargs):
        super(DataFrameArtifact, self).__init__(*args, **kwargs)
        self.pd = modin.pandas
        self._deserialization_function = {
            'csv': self.pd.read_csv
        }
        self._serialization_function = {
            'csv': 'to_csv'
        }

        self.operation_class = DataFrameOperation


class ModinWorkflow(Workflow):
    def __init__(self, *args, **kwargs):
        """
        Create a new workflow with a specified name
        :param name: Name of the workflow
        :param out_directory: Output Directory for this workflow
        :param wf_type: Type of Artifacts generated by this workflow (pandas|sql)
        """
        super(ModinWorkflow, self).__init__(*args, **kwargs)
        self.artifact_class = ModinArtifact
        self.operator_class = DataFrameOperation

    def initialize_new_artifact(self, label=None, filename=None):
        return ModinArtifact(label, filename=filename)
